### ISSUE TITLE
some mistakes of this code

### ISSUE THREAD

**Issue by Yanxing-Shi** [Near32/GazeboDomainRandom#1]
Hello, I'm sorry to bother you, I want to reproduce the experiment of the paper, but I have made these mistakes:
```
Traceback (most recent call last):
  File "createDataset-auto.py", line 1, in <module>
    from XMLGenerator import XMLGenerator, XMLObjectTags
  File "/home/user/xing/GazeboDomainRandom/src/XMLGenerator/__init__.py", line 2, in <module>
    from XMLGenerator import XMLObjectTags
ImportError: cannot import name 'XMLObjectTags'
```

**Comment by Near32** [comment]
Sorry for the late reply, #2 should solve this issue. I am assuming you are using a version 3.x of Python.
